filter:
    paths:
        - src/
        - tests/

tools:
    php_analyzer: true
    php_cpd: true
    php_mess_detector: true
    php_loc: true
    php_pdepend: true

build:
    image: default-bionic

    nodes:
        analysis:
            project_setup:
                override:
                    - "composer install --no-interaction --no-scripts --no-plugins"
            tests:
                override:
                    - php-scrutinizer-run

        tests:
            root_path: build
            commands:
                - command: |
                    composer install --no-interaction --no-scripts --no-plugins
                    XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=coverage.clover
                  coverage:
                      file: "coverage.clover"
                      format: "php-clover"
