build:
    image: default-bionic

    nodes:
        analysis:
            project_setup:
                override:
                    - "composer install --no-interaction --no-scripts --no-plugins"
            tests:
                override:
                    - php-scrutinizer-run

        tests:
            root_path: build
            project_setup:
                override:
                    - "composer install --no-interaction --no-scripts --no-plugins"
            commands:
                - command: |
                    XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=coverage.clover
                  coverage:
                      file: "coverage.clover"
                      format: "php-clover"
